apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 10-oot-ice
spec:
  config:
    ignition:
     version: 3.2.0
    storage:
      files:
        - contents:
            source: 'data:text/plain;charset=us-ascii;base64,IyEvYmluL2Jhc2gKc2V0IC1ldQoKQUNUSU9OPSQxOyBzaGlmdApJTUFHRT0kMTsgc2hpZnQKS0VSTkVMPWB1bmFtZSAtcmAKCnBvZG1hbiBwdWxsIC0tdGxzLXZlcmlmeT1mYWxzZSAtLWF1dGhmaWxlIC92YXIvbGliL2t1YmVsZXQvY29uZmlnLmpzb24gJHtJTUFHRX06JHtLRVJORUx9IDI+JjEKCmxvYWRfa21vZHMoKSB7CgogICAgcG9kbWFuIHJ1biAtaSAtLXByaXZpbGVnZWQgLXYgL2xpYi9tb2R1bGVzLyR7S0VSTkVMfS9rZXJuZWwvZHJpdmVycy86L2xpYi9tb2R1bGVzLyR7S0VSTkVMfS9rZXJuZWwvZHJpdmVycy8gJHtJTUFHRX06JHtLRVJORUx9IGxvYWQuc2gKfQp1bmxvYWRfa21vZHMoKSB7CiAgICBwb2RtYW4gcnVuIC1pIC0tcHJpdmlsZWdlZCAtdiAvbGliL21vZHVsZXMvJHtLRVJORUx9L2tlcm5lbC9kcml2ZXJzLzovbGliL21vZHVsZXMvJHtLRVJORUx9L2tlcm5lbC9kcml2ZXJzLyAke0lNQUdFfToke0tFUk5FTH0gdW5sb2FkLnNoCn0KCmNhc2UgIiR7QUNUSU9OfSIgaW4KICAgIGxvYWQpCiAgICAgICAgbG9hZF9rbW9kcwogICAgOzsKICAgIHVubG9hZCkKICAgICAgICB1bmxvYWRfa21vZHMKICAgIDs7CiAgICAqKQogICAgICAgIGVjaG8gIlVua25vd24gY29tbWFuZC4gRXhpdGluZy4iCiAgICAgICAgZWNobyAiVXNhZ2U6IgogICAgICAgIGVjaG8gIiIKICAgICAgICBlY2hvICJsb2FkICAgICAgICBMb2FkIGtlcm5lbCBtb2R1bGUocykiCiAgICAgICAgZWNobyAidW5sb2FkICAgICAgVW5sb2FkIGtlcm5lbCBtb2R1bGUocykiCiAgICAgICAgZXhpdCAxCmVzYWMK'
          filesystem: root
          mode: 493
          path: /usr/local/bin/oot-ice
    systemd:
      units:
      - contents: |
          [Unit]
          Description=out-of-tree driver loader
          # Start after the network is up
          Wants=network-online.target
          After=network-online.target
          # Also after docker.service (no effect on systems without docker)
          After=docker.service
          # Before kubelet.service (no effect on systems without kubernetes)
          Before=kubelet.service

          [Service]
          Type=oneshot
          RemainAfterExit=true
          # Use bash to workaround https://github.com/coreos/rpm-ostree/issues/1936
          ExecStart=/usr/bin/bash -c "/usr/local/bin/oot-ice load  registry.ran-vcl01.ptp.lab.eng.bos.redhat.com:5000/intel/oot-ice"
          ExecStop=/usr/bin/bash -c "/usr/local/bin/oot-ice unload registry.ran-vcl01.ptp.lab.eng.bos.redhat.com:5000/intel/oot-ice"
          StandardOutput=journal+console

          [Install]
          WantedBy=default.target
        enabled: true
        name: "oot-ice.service"
